theme: jekyll-theme-slate
title: OSVTAC Recommendations
description: San Francisco Open Source Voting System Technical Advisory
  Committee (OSVTAC) Recommendations
# Only render the README and CONTRIBUTE files on GitHub.
exclude: [CONTRIBUTE.md, README.md]
